### ISSUE TITLE
 NVIDIA-SMI Crash with Unraid 

### ISSUE THREAD

**Issue by LimesKey** [ich777/unraid-nvidia-driver#3]
I'm receiving some crashes from presumably the NVIDIA driver plugin in Unraid. I've run a short memtest already for about 24 hours, I can run one for longer if required. Pastebin for the crash is [here](https://pastebin.com/jG47Brrp). I did some research already and wasn't able to find much about this. My RAM is not ECC which I know is problematic but I'm hoping it's not a RAM issue.

```
Feb 19 21:53:17 Dragon kernel: BUG: unable to handle page fault for address: ffffc90011110200
Feb 19 21:53:17 Dragon kernel: #PF: supervisor write access in kernel mode
Feb 19 21:53:17 Dragon kernel: #PF: error_code(0x0002) - not-present page
Feb 19 21:53:17 Dragon kernel: PGD 100000067 P4D 100000067 PUD 100180067 PMD 0 
Feb 19 21:53:17 Dragon kernel: Oops: 0002 [#1] PREEMPT SMP NOPTI
Feb 19 21:53:17 Dragon kernel: CPU: 5 PID: 9577 Comm: nvidia-smi Tainted: P           O      5.19.17-Unraid #2
Feb 19 21:53:17 Dragon kernel: Hardware name: System manufacturer System Product Name/ROG STRIX B450-F GAMING II, BIOS 5003 02/03/2023
```

I am on the latest version of the plugin, and have NVIDIA driver `525.89.02` installed on my 2070 Super GPU. I rarely use the GPU and only use it for TDARR.

**Comment by ich777** [comment]
Please report this on the Unraid Forums with you Diagnostics attached.
