### ISSUE TITLE
/etc/nvidia-container-runtime/config.tom not present in your last driver packages

### ISSUE THREAD

**Issue by Peuuuur-Noel** [ich777/unraid-nvidia-driver#4]
Hello,

The "/run is full" issue happened to me again. You solved it by changing the log-level in `/etc/nvidia-container-runtime/config.toml`.
This file is not present in your last driver packages. Looks like nvidia-container-toolkit [doesn't create this file anymore](https://github.com/NVIDIA/nvidia-container-toolkit/issues/78).

Some ways to fix this:
- Add config file to driver package.
- In [nvidia-driver.plg](https://github.com/ich777/unraid-nvidia-driver/blob/master/nvidia-driver.plg#L373-L374), if config file doesn't exist, you can generate it with this command
`mkdir -p /etc/nvidia-container-runtime && nvidia-ctk config default > /etc/nvidia-container-runtime/config.toml`
or create it with this content:
```
[nvidia-container-runtime]
log-level = "warning"
```

Unraid: 6.12.4 (kernel: 6.1.49-Unraid)
Nvidia driver unraid plugin: 2023.08.31
Nvidia driver: 535.104.05 (ctk 1.14.0)

**Comment by ich777** [comment]
Sorry, my build machine pulled in the wrong nvidia-container-toolkit and therefore the file isn't there, you can see that the package that I've built has the file in it [here](https://github.com/ich777/nvidia-container-toolkit/releases/tag/1.14.0), but I really can't tell why it did pull in the wrong file. Hmmm, have to look into this.

I will trigger a rebuild from the Nvidia drivers which will take about an hour.

**Comment by ich777** [comment]
The build for the packages is now almost finished. I also pushed a update to the plugin itself for users who have the plugin currently installed but this of course means that they have to reboot at least once.

This file was never auto created in my build process btw, just read your full question and possible fix.

Thank you for the report, if you experience further issues feel free to open up a new issue.

**Comment by Peuuuur-Noel** [comment]
Thank for your help too and quick fix!
